<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => NULL,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => NULL,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'brick/math' => array(
            'pretty_version' => '0.11.0',
            'version' => '0.11.0.0',
            'reference' => '0ad82ce168c82ba30d1c01ec86116ab52f589478',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.5.1',
            'version' => '7.5.1.0',
            'reference' => 'b964ca597e86b752cd994f27293e9fa6b6a95ed9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.2',
            'version' => '1.5.2.0',
            'reference' => 'b94b2807d85443f9719887892882d0329d1e2598',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.5.0',
            'version' => '2.5.0.0',
            'reference' => 'b635f279edd83fc275f822a1188157ffea568ff6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'minishlink/web-push' => array(
            'pretty_version' => 'v8.0.0',
            'version' => '8.0.0.0',
            'reference' => 'ec034f1e287cd1e74235e349bd017d71a61e9d8d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../minishlink/web-push',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/constant_time_encoding' => array(
            'pretty_version' => 'v2.6.3',
            'version' => '2.6.3.0',
            'reference' => '58c3f47f650c94ec05a151692652a868995d2938',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/constant_time_encoding',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '0955afe48220520692d2d09f7ab7e0f93ffd6a31',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'e616d01114759c4c489f93b099585439f795fe35',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spomky-labs/base64url' => array(
            'pretty_version' => 'v2.0.4',
            'version' => '2.0.4.0',
            'reference' => '7752ce931ec285da4ed1f4c5aa27e45e097be61d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spomky-labs/base64url',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'spomky-labs/pki-framework' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => 'd3ba688bf40e7c6e0dabf065ee18fc210734e760',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spomky-labs/pki-framework',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.2.1',
            'version' => '3.2.1.0',
            'reference' => 'e2d1534420bd723d0ef5aec58a22c5fe60ce6f5e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'web-token/jwt-core' => array(
            'pretty_version' => '3.1.7',
            'version' => '3.1.7.0',
            'reference' => 'ec2580e8cdd17410016216fbf1b645052c35f644',
            'type' => 'library',
            'install_path' => __DIR__ . '/../web-token/jwt-core',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'web-token/jwt-key-mgmt' => array(
            'pretty_version' => '3.1.7',
            'version' => '3.1.7.0',
            'reference' => 'bf6dec304f2a718d70f7316e498c612317c59e08',
            'type' => 'library',
            'install_path' => __DIR__ . '/../web-token/jwt-key-mgmt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'web-token/jwt-signature' => array(
            'pretty_version' => '3.1.7',
            'version' => '3.1.7.0',
            'reference' => '14b71230d9632564e356b785366ad36880964190',
            'type' => 'library',
            'install_path' => __DIR__ . '/../web-token/jwt-signature',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'web-token/jwt-signature-algorithm-ecdsa' => array(
            'pretty_version' => '3.1.7',
            'version' => '3.1.7.0',
            'reference' => 'e09159600f19832cf4a68921e7299e564bc0eaf9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../web-token/jwt-signature-algorithm-ecdsa',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'web-token/jwt-util-ecc' => array(
            'pretty_version' => '3.1.7',
            'version' => '3.1.7.0',
            'reference' => 'b2337052dbee724d710c1fdb0d3609835a5f8609',
            'type' => 'library',
            'install_path' => __DIR__ . '/../web-token/jwt-util-ecc',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
