<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit44cd4c9a6e09722d3319d662975b5c1b
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit44cd4c9a6e09722d3319d662975b5c1b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit44cd4c9a6e09722d3319d662975b5c1b::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit44cd4c9a6e09722d3319d662975b5c1b::$classMap;

        }, null, ClassLoader::class);
    }
}
