<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf8dd5ced018533dcbb99a0e2089e69df
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf8dd5ced018533dcbb99a0e2089e69df::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf8dd5ced018533dcbb99a0e2089e69df::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf8dd5ced018533dcbb99a0e2089e69df::$classMap;

        }, null, ClassLoader::class);
    }
}
