<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb75465c39417c97196984bf469eeb868
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb75465c39417c97196984bf469eeb868::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb75465c39417c97196984bf469eeb868::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb75465c39417c97196984bf469eeb868::$classMap;

        }, null, ClassLoader::class);
    }
}
